name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output publish --no-build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: publish

  deploy:
    needs: build
    runs-on: self-hosted # Uses the self-hosted runner on your Windows Server

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: C:\GitHubActions\publish

      - name: Deploy to IIS
        run: |
          Stop-Service -Name 'w3svc'
          # Remove old files
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\SchoolMgtSystem\Publish\*" 
          # Copy new files
          Copy-Item -Recurse -Path "C:\GitHubActions\publish\*" -Destination "C:\inetpub\wwwroot\SchoolMgtSystem\Publish\" 
          # Start IIS
          Start-Service -Name 'w3svc'
        shell: powershell

      - name: Restart IIS Site
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "SchoolManagementSystem"
          Restart-WebSite -Name "SchoolManagementSystem"
        shell: powershell
